apiVersion: v1
kind: Pod
metadata:
  name: firefox
  labels:
    app: firefox
spec:
  containers:
  - name: firefox
    image: selenium/standalone-firefox:latest
    ports:
    - containerPort: 4444   # Selenium WebDriver API
    - containerPort: 5900   # VNC GUI (browser GUI access ke liye)
---
apiVersion: v1
kind: Service
metadata:
  name: firefox-service
spec:
  type: LoadBalancer
  selector:
    app: firefox
  ports:
  - name: selenium
    port: 4444
    targetPort: 4444
  - name: vnc
    port: 5900
    targetPort: 5900
