apiVersion: v1
kind: Pod
metadata:
  name: simple-web
  labels:
    app: simple-web
spec:
  containers:
  - name: simple-web
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-service
spec:
  type: LoadBalancer
  selector:
    app: simple-web
  ports:
  - port: 80
    targetPort: 80
