apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
spec:
  nodeSelector:
    kubernetes.io/hostname: aks-agentpool-25861202-vmss000001
  containers:
  - name: agent
    image: openjdk:11
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: jenkins-home
      mountPath: /home/jenkins
  volumes:
  - name: jenkins-home
    emptyDir: {}
  restartPolicy: Never
